### ISSUE TITLE
Web worker slower?

### ISSUE THREAD

**Issue by quanghoc** [afshinm/50k#1]
Is that true that using web worker is slower in this case? I am on Chrome with Macbook

**Comment by afshinm** [comment]
The reason I made this test is to show the busy time of the browser, when you perform the action on the current thread, instead of creating another thread.

When you use web worker to sort the array, browser creates a new thread and executes the bubble sort algorithm on that thread. That's why you can see the progress-bar while sorting with web worker! :-)

**Comment by quanghoc** [comment]
That's not my question though

**Comment by edysegura** [comment]
Hi @quanghoc! It is a little bit slower but the positive thing here is to not block the main thread and let the user do other tasks while wait for a response.

Please [read this article](http://www.html5rocks.com/en/tutorials/workers/basics/) to understand the propose of Web Workers.

**Comment by srcspider** [comment]
@afshinm @edysegura your page title is "Sorting 50K Array with Bubble Sort" and you show the time is takes. Even if we bother to read the "you can't do anything on the page" (what's there to do, you didn't really add anything on it anyway), the page implies that somehow the webworker is suppose to be faster not that it's a test of how fast a loading bar shows.

In fact that loading bar is just a pointless infinite spinner so as far as I'm concerned you can get that to show even with out the web worker since you can just make it display first. I get why it's trying to show but this demo does a very poor job of showing it. You have to be well versed in what the demo tries to show to even realize it's trying to do that.

The 50k array is a extremely strange use case too. When do you ever have that? I can understand pre-loading in data for a listing or data in a graph but a human can't perceive that much data with their eyeballs so this is mostly showing how much of a bad idea it is not to simplify data to the essentials rather then any practical use case. Even in a database, when you have a ton of data you ensure you have an additional data structure such as an index to make it fast. _As soon as you accept that the case of performing CPU burn calculations on the client_ is nonsensical, then  you suddenly don't really have this issue, since there is time for other things to jump into the event loop.
